# Load Library

In [1]:
import pandas as pd
import numpy as np
import warnings
from sklearn.decomposition import TruncatedSVD
from scipy.sparse.linalg import svds

warnings.filterwarnings('ignore')

# SVD -> 피어슨 상관계수를 이용한 추천

In [2]:
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')

In [3]:
rating_movie = pd.merge(ratings, movies, on='movieId')

In [4]:
rating_movie

userId  ...                                genres
0            1  ...                                 Drama
1            7  ...                                 Drama
2           31  ...                                 Drama
3           32  ...                                 Drama
4           36  ...                                 Drama
...        ...  ...                                   ...
99999      664  ...                         Action|Sci-Fi
100000     664  ...  Drama|Horror|Mystery|Sci-Fi|Thriller
100001     665  ...                        Comedy|Romance
100002     665  ...                  Comedy|Drama|Romance
100003     668  ...                                Comedy

[100004 rows x 6 columns]

In [8]:
user_movie_rating = pd.pivot_table(rating_movie, index='userId', columns='title', values='rating').fillna(0)

In [9]:
user_movie_rating

title   "Great Performances" Cats (1998)  ...  İtirazım Var (2014)
userId                                    ...                     
1                                    0.0  ...                  0.0
2                                    0.0  ...                  0.0
3                                    0.0  ...                  0.0
4                                    0.0  ...                  0.0
5                                    0.0  ...                  0.0
...                                  ...  ...                  ...
667                                  0.0  ...                  0.0
668                                  0.0  ...                  0.0
669                                  0.0  ...                  0.0
670                                  0.0  ...                  0.0
671                                  0.0  ...                  0.0

[671 rows x 9064 columns]

In [13]:
movie_user_rating = user_movie_rating.values.T

In [15]:
movie_user_rating.shape

(9064, 671)

In [17]:
# TruncatedSVD를 사용해 차원 축소
SVD = TruncatedSVD(n_components=12)
matrix = SVD.fit_transform(movie_user_rating)
matrix.shape

(9064, 12)

In [18]:
corr = np.corrcoef(matrix)

In [25]:
movie_title = user_movie_rating.columns
movie_corr_df = pd.DataFrame(corr, columns=movie_title, index=movie_title)

In [28]:
def movie_recommend_by_corr(title, num):
  return movie_corr_df[title].sort_values(ascending=False)[1:num+1]

In [31]:
movie_title = "Guardians of the Galaxy (2014)"
num = 10
movie_recommend_by_corr(movie_title, num)

title
Iron Man 2 (2010)                            0.993868
Edge of Tomorrow (2014)                      0.992542
Avengers, The (2012)                         0.984908
X-Men: Days of Future Past (2014)            0.970323
Indie Game: The Movie (2012)                 0.969312
The Hunger Games (2012)                      0.968075
Captain America: The First Avenger (2011)    0.965777
X-Men: First Class (2011)                    0.962607
Drillbit Taylor (2008)                       0.960245
Paperboy, The (2012)                         0.960245
Name: Guardians of the Galaxy (2014), dtype: float64

# Matrix Factorization을 이용한 사용자 개인 추천

In [39]:
# user-movie 데이터프레임을 matrix로 변경
user_movie_rating_matrix = user_movie_rating.values
print(user_movie_rating_matrix)
print(user_movie_rating_matrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(671, 9064)


In [41]:
# user별 영화 평균 평점 
user_rating_mean = np.mean(, axis=1)user_movie_rating_matrix

In [44]:
# user-movie matrix에서 유저별 평균 평점을 빼줌
user_movie_rating_matrix_scaled = user_movie_rating_matrix - user_rating_mean.reshape(-1,1)

In [45]:
user_movie_rating_matrix_scaled

array([[-0.00562665, -0.00562665, -0.00562665, ..., -0.00562665,
        -0.00562665, -0.00562665],
       [-0.02923654, -0.02923654, -0.02923654, ..., -0.02923654,
        -0.02923654, -0.02923654],
       [-0.02007944, -0.02007944, -0.02007944, ..., -0.02007944,
        -0.02007944, -0.02007944],
       ...,
       [-0.01368049, -0.01368049, -0.01368049, ..., -0.01368049,
        -0.01368049, -0.01368049],
       [-0.01301853, -0.01301853, -0.01301853, ..., -0.01301853,
        -0.01301853, -0.01301853],
       [-0.04970212, -0.04970212, -0.04970212, ..., -0.04970212,
        -0.04970212, -0.04970212]])

In [46]:
# scipy의 TruncatedSVD를 이용해 행렬 분해
# sklearn과 차이점 : scipy의 TruncatedSVD는 U, sigma, Vt값을 반환해주는 반면 sklearn은 반환해주지 않음
U, sigma, Vt = svds(user_movie_rating_matrix_scaled, k=12)

In [48]:
print(U.shape)
print(sigma.shape)
print(Vt.shape)

(671, 12)
(12,)
(12, 9064)


In [51]:
# sigma를 대각행렬로 변경
sigma = np.diag(sigma)

In [54]:
# 분해한 행렬을 다시 곱한 후 유저 평균 평점 값을 더해 줌
svd_user_predicted_ratings = np.dot(np.dot(U, sigma),Vt) + user_rating_mean.reshape(-1,1)

In [58]:
svd_user_predicted_ratings_df = pd.DataFrame(svd_user_predicted_ratings, index=user_movie_rating.index, columns=user_movie_rating.columns)

In [60]:
svd_user_predicted_ratings_df

title   "Great Performances" Cats (1998)  ...  İtirazım Var (2014)
userId                                    ...                     
1                              -0.004829  ...            -0.006070
2                               0.001307  ...            -0.004992
3                               0.011559  ...             0.014686
4                              -0.010664  ...            -0.031358
5                              -0.020953  ...            -0.032757
...                                  ...  ...                  ...
667                            -0.002066  ...            -0.001158
668                             0.005654  ...             0.009182
669                            -0.000721  ...            -0.000152
670                             0.003619  ...             0.006703
671                             0.016189  ...             0.014721

[671 rows x 9064 columns]

In [119]:
# 개인화 추천 함수
def movie_recommend_by_user(user_id, org_movies_df, predicted_ratings_df, movie_info, num_recommend):
  """
  input : userid, org_movies_df, predicted_ratings_df, num_recommend
  output : recommended movies by user
  description : user_id별로 본 영화를 제외하고 예측결과 순으로 영화 추천
  """

  # predicted_ratings_df에서 해당 user가 안본 영화만 선택
  unseen_movie_index = org_movies_df.transpose()[user_id] == 0
  unseen_movie = predicted_ratings_df.transpose()[user_id][unseen_movie_index].sort_values(ascending=False)

  recommneded_movie_list = pd.DataFrame(unseen_movie[:num_recommend]).reset_index().rename(columns={user_id:'predicted'})
  recommneded_movie_list_with_info = pd.merge(movie_info, recommneded_movie_list, how='right', on='title')

  return recommneded_movie_list_with_info



In [121]:
movie_recommend_by_user(330, user_movie_rating, svd_user_predicted_ratings_df, movies, 10)

movieId  ... predicted
0      296  ...  2.059987
1      356  ...  1.772624
2      608  ...  1.526693
3      590  ...  1.508757
4      380  ...  1.276502
5       47  ...  1.265067
6      377  ...  1.141936
7      260  ...  1.077095
8      357  ...  1.065929
9      592  ...  1.048694

[10 rows x 4 columns]